### ISSUE TITLE
通知: 版本2.1.6(2.1.6.173.183/2.1.6.183.0)出现兼容性BUG!!!

### ISSUE THREAD

**Issue by tangcent** [tangcent/easy-yapi#363]
- 请升级至:  [v2.1.8](https://plugins.jetbrains.com/plugin/12458-easyyapi/versions/stable/112985)

- 手动下载新的包:  [v2.1.8](https://github.com/tangcent/easy-yapi/releases/tag/v2.1.8)

---

已知BUG:

- [X] 生成的接口名称由原来的 只导出第一行注释变成了 所有注释 (#360)
- [X] java.validation(grouped)的是否必填控制失效了，生成的所有文档属性都是非必填了 (#360)
- [X] 字段注释丢失 (#362)
- [X] error to parse[xxx] as Querys (https://github.com/tangcent/easy-yapi/issues/363#issuecomment-791395897)

---

计划:

- [X] 补充基础包的单元测试: [intellij-kotlin/pulls](https://github.com/Earth-1610/intellij-kotlin/pulls?q=is%3Apr++add+test+case+)
- [ ] 探索插件整体测试
- [x]  rc版到正式版间禁止任何优化
- [x] 探索插件自动化发布

**Comment by PassXml** [comment]
好像可以用了..但是还是会报错

```
error to parse[xxx] as Querys
[TRACE]	java.lang.ClassCastException: class java.util.HashMap cannot be cast to class com.itangcent.common.utils.KV (java.util.HashMap is in module java.base of loader 'bootstrap'; com.itangcent.common.utils.KV is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5d6c8b1f)
```
